baseurl = "https://pipit.me/"
title = "Bruce.Y"
theme = "hugo-theme-console"
languageCode = "en-us"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
  [languages.zh]
    languageName = "中文"
    languageCode = "zh-cn"
    weight = 2

[params]
  titleCutting = false
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

  [[params.navlinks]]
  name = "notes/"
  url = "notes/"

  [[params.navlinks]]
  name = "photos/"
  url = "photos/"
